extends Node
## Procedural audio manager (autoload "Audio").
## All SFX are preloaded WAVs generated by tools/gen_audio.py.

const SFX_POOL_SIZE := 10

## Explicit manifest — DirAccess on res://audio/ does not enumerate inside
## exported pck files, so every stream is preloaded by path.
const STREAMS := {
	"jump": "res://audio/jump.wav",
	"land": "res://audio/land.wav",
	"drink": "res://audio/drink.wav",
	"ship": "res://audio/ship.wav",
	"hit": "res://audio/hit.wav",
	"stun": "res://audio/stun.wav",
	"drain": "res://audio/drain.wav",
	"coin": "res://audio/coin.wav",
	"boss_alarm": "res://audio/boss_alarm.wav",
	"boss_hit": "res://audio/boss_hit.wav",
	"over": "res://audio/over.wav",
	"click": "res://audio/click.wav",
	"start": "res://audio/start.wav",
	"powerup": "res://audio/powerup.wav",
	"teleport": "res://audio/teleport.wav",
	"music": "res://audio/music.wav",
}

var _streams := {}
var _pool: Array[AudioStreamPlayer] = []
var _pool_index := 0
var _music_player: AudioStreamPlayer
var _music_started := false


func _ready() -> void:
	for key in STREAMS:
		_streams[key] = load(STREAMS[key])

	for i in SFX_POOL_SIZE:
		var p := AudioStreamPlayer.new()
		p.bus = "Master"
		add_child(p)
		_pool.append(p)

	_music_player = AudioStreamPlayer.new()
	_music_player.stream = _streams.get("music")
	_music_player.volume_db = -14.0
	add_child(_music_player)

	_apply_mute(Save.is_muted())


func play(sfx: StringName, volume_db: float = 0.0) -> void:
	if not _streams.has(sfx):
		push_warning("Unknown sfx: %s" % sfx)
		return
	if Save.is_muted():
		return
	var player := _pool[_pool_index]
	_pool_index = (_pool_index + 1) % _pool.size()
	player.stream = _streams[sfx]
	player.volume_db = volume_db
	player.play()


func start_music() -> void:
	if _music_started:
		return
	_music_started = true
	if not Save.is_muted():
		_music_player.play()


func stop_music() -> void:
	_music_player.stop()


func toggle_mute() -> bool:
	var muted := not Save.is_muted()
	Save.set_muted(muted)
	_apply_mute(muted)
	return muted


func _apply_mute(muted: bool) -> void:
	if muted:
		_music_player.stop()
	else:
		if _music_started:
			_music_player.play()
